import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { cn } from "../libs/utils";
import Navbar from "@/components/Navbar";

const montserrat = Montserrat({ subsets: ["latin"], variable: '--font-mon', display: 'swap' });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(montserrat.variable, 'bg-slate-300', 'p-5')}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
